export enum ActionTypes {
  SET_PRODUCTS = 'SET_PRODUCTS',
  SELECTED_PRODUCT = 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT',
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  UPDATE_CART = 'UPDATE_CART',
  CLEAR_CART = 'CLEAR_CART',
  SET_QTY_ITEM = 'SET_QTY_ITEM',
  SET_MODAL_DISPLAY = 'SET_MODAL_DISPLAY',
  CHANGE_LANG = 'CHANGE_LANG',
  TOGGLE_DARKTHEME = 'TOGGLE_DARKTHEME'
}
